### ISSUE TITLE
Please provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [bhrigu123/Instant-Lyrics#3]
Currently it is quite complicated to install Instant-Lyrics, with [many manual steps](http://www.omgubuntu.co.uk/2017/03/get-lyrics-spotify-track-ubuntu-desktop):

![install](https://cloud.githubusercontent.com/assets/2480569/24086207/a8c6aea4-0d0b-11e7-80c5-d73cb1979f66.png)

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

I generated a test AppImage for Instant-Lyrics:
https://bintray.com/probono/AppImages/Instant_Lyrics/_latestVersion#files
Just download, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run. Should work on most 2014-ish and later distributions. Some fine-tuning may be needed.

Here is a yml file that controls the AppImage generation:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/Instant-Lyrics.yml

To run it, do the following on a Ubuntu or Debian system:

```
wget https://github.com/probonopd/AppImages/raw/master/recipes/meta/Recipe
bash -ex Recipe Instant-Lyrics
```

This will grab the latest version of Instant-Lyrics from this GitHub repository and produce an AppImage.

**Comment by probonopd** [comment]
Such a relief to see this button now:

![screenshot from 2017-03-22 00-07-28](https://cloud.githubusercontent.com/assets/2480569/24174894/96eb6bbe-0e93-11e7-8093-de308d7f767c.png)

So, would you like to provide an official one?

**Comment by bhrigu123** [comment]
Hi,
I just tested out the AppImage on my computer, and it's working fine. I just had a few questions/clarifications:

1. To create an AppImage in the future, I would need to run the command `bash -ex Recipe Instant-Lyrics`,  which I guess will do the following:

- Fetch the packages as listed in the https://github.com/probonopd/AppImages/blob/master/recipes/meta/Instant-Lyrics.yml and fetch the latest Instant-Lyrics from the master branch (as mentioned in your yml) and create an AppImage, which I should add to my Releases. 
Right?


2. It is not showing the icon when it adds Instant Lyrics to desktop apps entry.
![appimage](https://cloud.githubusercontent.com/assets/6123105/24186370/0214409a-0efe-11e7-8029-80748daf5a09.jpeg)

**Comment by probonopd** [comment]
Can you please point me to a 256x256 px application icon in your repository that we can put into `./usr/share/icons/hicolor/256x256/apps/instantlyrics.png`?

**Comment by bhrigu123** [comment]
ah! I hadn't maintained the icons properly. Hold up; I'll need to add some more resolutions icons. I'll let you know.

**Comment by bhrigu123** [comment]
Added the 256x256 png at
https://github.com/bhrigu123/Instant-Lyrics/blob/master/icons/instant-lyrics-256.png

**Comment by probonopd** [comment]
Updated https://github.com/probonopd/AppImages/blob/master/recipes/meta/Instant-Lyrics.yml

**Comment by bhrigu123** [comment]
Great.

So, just to confirm, to create a new AppImage, I just need to run `bash -ex Recipe Instant-Lyrics`, which will automatically fetch the latest master branch of my repo. (which I should add to my releases). right?

**Comment by probonopd** [comment]
That is correct @bhrigu123

**Comment by bhrigu123** [comment]
Oh cool.

I'm finishing up on some changes and will update the repo soon.

**Comment by bhrigu123** [comment]
Done.

**Comment by probonopd** [comment]
Works like a charm for me. Thank you for this useful app!

**Comment by bhrigu123** [comment]
Hey, @probonopd , the AppImage stopped working suddenly. When I tried running it from the terminal I'm now getting this error:

``` sh
./Instant_Lyrics-git.e3c0cc2.glibc2.15-x86_64.AppImage 
/bin/bash: ../lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
Traceback (most recent call last):
  File "/tmp/.mount_kGRBO8/usr/bin/instantlyrics", line 2, in <module>
    import gi
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib/python2.7/dist-packages/gi/_gi.x86_64-linux-gnu.so: undefined symbol: g_irepository_get_immediate_dependencies
```

**Comment by probonopd** [comment]
```
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib/python2.7/dist-packages/gi/_gi.x86_64-linux-gnu.so: undefined symbol: g_irepository_get_immediate_dependencies
```

suggests that files are being loaded from /usr rather than from inside the AppImage. Need to find out the reason for this and change it.

**Comment by probonopd** [comment]
Could this change be the culprit?
https://github.com/probonopd/AppImages/commit/020e0a3eaaea3db337a48628b8ebd347206b188a

**Comment by bhrigu123** [comment]
um...I can't be much sure about the Recipe file.

Although, how can an AppImage, which was running fine previously, would suddenly stop working? I mean that AppImage file has already been bundled/compiled. And no changes can be done to it now. So how can that same file stop to work like before?

**Comment by probonopd** [comment]
So, you are saying you did not make or download a new AppImage, but the existing one suddenly stopped working?

In this case, something on your system must have changed, since AppImages are immutable (=read-only).

**Comment by bhrigu123** [comment]
Yes, that is correct. The existing AppImage stopped working.
I don't think I did anything that could cause changes to my system.

Also, when I'm running my app directly from source (the python file) then it is working just fine.
So if it can run from the Python file, I think the system must be fine.

**Comment by probonopd** [comment]
The one on your GitHub Releases page works fine for me on KDE neon User Edition 5.9:

![screenshot_20170326_183626](https://cloud.githubusercontent.com/assets/2480569/24333122/38b96de8-1253-11e7-998a-fc8d843c9e18.png)

**Comment by bhrigu123** [comment]
Oh, okay. 
The same file is not running on mine. Not sure why.
Let me just see if it is working on some more systems also, or is it just me.

**Comment by kareemamrr** [comment]
What is the command for Fedora25? Please help.

**Comment by bhrigu123** [comment]
@kareemamrr1203 Are you trying to install from AppImage or from Source?
At the moment, the AppImage is of older version. To get latest version, install from source.

If you are installing from AppImage:
- Download the `.AppImage` file from [releases](https://github.com/bhrigu123/Instant-Lyrics/releases) of v1.0.
- Open terminal. Go to directory where the file is downloaded. Run:
 `chmod a+x filename.AppImage`
- Run the file using the command: `./filename.AppImage`

To install and run from source, instructions are given in README.

**Comment by kareemamrr** [comment]
I followed the instructions but at the last step it just does nothing, thoughts? 
![screenshot-20170404174811-734x490](https://cloud.githubusercontent.com/assets/26971543/24763340/c1bfde98-1af9-11e7-8056-e3957bd7cfdf.png)

**Comment by bhrigu123** [comment]
Yes it will not display any message on the terminal.
After running the command, there should be a new icon appearing on the Indicator Panel (System Tray). See if it's there.

(Also, create a New issue if there's still problem. This issue was for AppImage)

**Comment by kareemamrr** [comment]
i'm sorry I don't know how im new here :D  but no icon is appearing on the tray still
![screenshot-20170404175631-267x127](https://cloud.githubusercontent.com/assets/26971543/24763685/c592d9ca-1afa-11e7-8ed8-805700f6970b.png)

**Comment by bhrigu123** [comment]
Oh....I see. 
I've not tested on Fedora yet, and am not much a Fedora guy.

Are there some different Sessions/Display Supports in Fedora. Like Wayland, X11 or Xorg.
Try running on a different Session. Because someone else also had an issue. See this: #4 

I'll soon test on Fedora and see to it.

**Comment by probonopd** [comment]
@kareemamrr1203 did the AppImage work for you?

**Comment by probonopd** [comment]
Ping - how do you want to proceed with this?
